FROM ros:noetic

LABEL org.opencontainers.image.authors="ohin"
ENV RUNNING_IN_DOCKER true
ARG USER
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y \
    git \
    sudo \
    curl \
    wget \
    usbutils \
    v4l-utils \
    software-properties-common \
    ros-noetic-tf2-ros \
    ros-noetic-cv-bridge \
    ros-noetic-image-geometry \
    ros-noetic-image-transport \
    ros-noetic-eigen-conversions \
    ros-noetic-tf2-geometry-msgs \
    ros-noetic-camera-info-manager \
    ros-noetic-camera-calibration-parsers \
    && apt clean -y && rm -rf /var/lib/apt/lists/*

RUN groupadd --gid $USER_GID $USER \
    && useradd --uid $USER_UID --gid $USER_GID -ms /bin/bash $USER \
    && usermod -aG sudo,video $USER \
    && echo "$USER ALL=(ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/$USER \
    && echo "source /opt/ros/noetic/setup.bash" >> /home/$USER/.bashrc
    
USER $USER
WORKDIR /home/$USER/vision_ws

CMD [ "/bin/bash" ]