services:
  realsense: &vision_tutorial
    build:
      context: .
      target: realsense  
      args:
        USER: realsense
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
   
    image: vision_tutorial:realsense
    container_name: realsense
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD/../ws/realsense_pkg:/home/realsense/vision_ws/src/realsense-ros
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/bus/usb
    command: bash

  aruco:
    <<: *vision_tutorial
    build:
      context: .
      target: aruco 
      args:
        USER: aruco
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    image: vision_tutorial:aruco
    container_name: aruco
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD/../ws/aruco_pkg:/home/aruco/vision_ws/src/aruco_ros
    environment:
      - DISPLAY=${DISPLAY}
    command: bash