FROM ros:noetic AS base
LABEL org.opencontainers.image.authors="ohin"
ENV RUNNING_IN_DOCKER true
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y \
    git \
    sudo \
    curl \
    wget \
    usbutils \
    v4l-utils \
    software-properties-common \
    ros-noetic-tf \
    ros-noetic-tf2-ros \
    ros-noetic-tf2-geometry-msgs \
    ros-noetic-cv-bridge \
    ros-noetic-image-geometry \
    ros-noetic-image-transport \
    ros-noetic-eigen-conversions \
    ros-noetic-camera-info-manager \
    ros-noetic-ddynamic-reconfigure \
    ros-noetic-camera-calibration-parsers \
    && apt clean -y && rm -rf /var/lib/apt/lists/*

FROM base AS realsense
ARG USER
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN git clone --branch v2.50.0 https://github.com/IntelRealSense/librealsense.git /opt/librealsense 
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y \
    ros-noetic-diagnostic-updater \
    libgl1-mesa-glx libssl-dev libusb-1.0-0-dev libudev-dev pkg-config libgtk-3-dev \
    libqt5gui5 libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev at \
    && apt clean -y && rm -rf /var/lib/apt/list/*
#Install Intel RealSense SDK 2.0(v2.50.0)
WORKDIR /opt/librealsense/build
RUN cmake ../ -DBUILD_EXAMPLES=true -DCMAKE_BUILD_TYPE=Release \
    && make -j4 && sudo make install
RUN groupadd --gid $USER_GID $USER \
    && useradd --uid $USER_UID --gid $USER_GID -ms /bin/bash $USER \
    && usermod -aG sudo,video $USER \
    && echo "$USER ALL=(ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/$USER \
    && echo "source /opt/ros/noetic/setup.bash" >> /home/$USER/.bashrc
RUN mkdir -p /home/$USER/vision_ws/src && cd /home/$USER/vision_ws/src \
    && git clone --branch 2.3.2 https://github.com/IntelRealSense/realsense-ros.git \
    && cd /home/$USER/vision_ws \
    && /bin/bash -c "source /opt/ros/noetic/setup.bash && catkin_make"
USER $USER
WORKDIR /home/$USER/vision_ws
CMD [ "/bin/bash" ]

FROM base AS aruco 
ARG USER
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USER \
    && useradd --uid $USER_UID --gid $USER_GID -ms /bin/bash $USER \
    && usermod -aG sudo,video $USER \
    && echo "$USER ALL=(ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/$USER \
    && echo "source /opt/ros/noetic/setup.bash" >> /home/$USER/.bashrc
RUN mkdir -p /home/$USER/vision_ws/src && cd /home/$USER/vision_ws/src \
    && git clone --branch noetic-devel https://github.com/pal-robotics/aruco_ros.git \
    && cd /home/$USER/vision_ws \
    && /bin/bash -c "source /opt/ros/noetic/setup.bash && catkin_make"
USER $USER
WORKDIR /home/$USER/vision_ws
CMD [ "/bin/bash" ]
